spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true
  config:
    import: "optional:file:.env"
  thymeleaf:
    prefix: "classpath:/templates/"
    suffix: ".html"
    cache: false
    check-template-location: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
      springframework:
        core:
          env: DEBUG
        security: DEBUG


